version: '3.8'

services:

  gestiondesstock-db:
    image: "mariadb:10.6.5"
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - gestiondesstock-db:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  gestiondesstock-db:
    external: true